### ISSUE TITLE
taginfo showing different percentages for same tag in 2 places

### ISSUE THREAD

**Issue by georg-d** [taginfo/taginfo#315] opened 2021-01-30 11:02 UTC
The percentage of objects carrying a given key/tag differs massively between the display in the wiki page (e.g. https://wiki.openstreetmap.org/wiki/Tag:route%3Dpiste) and in "taginfo itself" (e.g. https://taginfo.openstreetmap.org/tags/route=piste#overview). 
![106325146-a349ff80-627a-11eb-8c7c-8544197146e6](https://user-images.githubusercontent.com/45993293/106354322-49d0e780-62f1-11eb-8653-7b00a860b5b1.png)
As a user, I'd expect percentages being the same both times, because the absolute numbers are similar, so the percent shall also be similar. If they are intended to be different, the difference shall be transported somehow e.g. via ? icon that opens a bubble help on mouse over.

I've the impression, once the statsistic may be computed by dividing by count of all objects and once by dividing only only the ones tagged with that key, but it may also be something different.

**Comment by matkoniecz** [comment] 2021-03-28 08:50
Note that it is possible that taginfo is innocent and OSM Wiki is broken. You may want to report it at https://wiki.openstreetmap.org/wiki/Talk:Wiki (or maybe it is already reported? It may be useful to check also archives)

**Comment by joto** [comment] 2021-03-28 09:56
@matkoniecz Both numbers are generated by taginfo.

Duplicate of #308.

**Closed** 2022-05-28 08:41 UTC
