### ISSUE TITLE
Wiki Tag:key=value sometimes not displayed in a link?

### ISSUE THREAD

**Issue by mnalis** [taginfo/taginfo#414] opened 2023-06-09 13:54 UTC
e.g. https://taginfo.openstreetmap.org/keys/medical_system%3Awestern#wiki under _"Wiki page"_ column shows just `→` for both languages:

![Screenshot 2023-06-09 at 15-34-43 medical_system western Keys OpenStreetMap Taginfo](https://github.com/taginfo/taginfo/assets/156656/b20914b3-4aea-4428-b7a5-d5b4c225a82f)

while I would expect it to show  `→ Key:medical_system:western` and `→ RU:Key:medical_system:western"` instead (like it does for other wiki pages). 

That makes it harder to read/navigate, and much harder to click.

Is it perhaps because of `:` in key name, or something else? Could it be fixed?

_(I've only found this possibly related issue https://github.com/taginfo/taginfo/issues/171, but the description on that wiki seems all normal ASCII.)_

**Comment by joto** [comment] 2023-06-13 10:47
The problem is that the width of that table column is not enough to show the very long wiki page name. You can see this if you grab the deviding line between columns and move it to the right, the table will resize and the full link appears. This is, of course, not good and should be fixed.

This is not related to #171.

**Closed** 2023-07-12 13:30 UTC
