### ISSUE TITLE
wish: allow to filter combinations via website URL itself

### ISSUE THREAD

**Issue by mnalis** [taginfo/taginfo#409] opened 2023-05-03 15:20 UTC
For example, I can open https://taginfo.openstreetmap.org/tags/highway=footway#combinations
and then type `oneway` in the table filter field, and taginfo.openstreetmap.org website will happily make this [API call](https://taginfo.openstreetmap.org/api/4/tag/combinations?key=highway&value=footway&filter=all&sortname=to_count&sortorder=desc&rp=10&page=1&query=oneway) and display only that subset of tags which contain word `oneway`, and occur in combination `highway=footway`.

However, often in [community discussions](https://community.openstreetmap.org/) it would be very useful to link to such resource **directly**  (for example via URL like https://taginfo.openstreetmap.org/tags/highway=footway#combinations/oneway or something similar).

---

Example, currently one has to write:
- to see how often `oneway` is used on `highway=footway` visit this [link](https://taginfo.openstreetmap.org/tags/highway=footway#combinations) and then type `oneway` in search form (not the top one, but one at the level of the table) and press `enter`

and I'd love to be able to write this instead:
- to see how often `oneway` is used on `highway=footway` visit this [link](https://taginfo.openstreetmap.org/tags/highway=footway#combinations/oneway).

Using the former is too clumsy and error prone (especially if one wants to point to several such resources for comparison!), often ending in writing overpass queries to do the same (but they are way too resource intensive, and often fail/timeout, so are often not an option).

**Comment by joto** [comment] 2023-05-04 06:43
Duplicate of #130. Closing here.

**Closed** 2023-06-18 13:42 UTC
