### ISSUE TITLE
Description wiki templates & Wikidata & Taginfo

### ISSUE THREAD

**Issue by drmx** [taginfo/taginfo#377] opened 2022-10-03 18:48 UTC
Hello! The Wiki **{{Key/ValueDescription}}** templates allows to display a tag information box on the wiki. If the template has no parameters (**{{ValueDescription}}** only, no  any **|parameter=value**) then the wiki shows full info from the wikidata, but Taginfo doesn't show anything.

For example wiki article [_RU:Tag:amenity=animal_shelter_](https://wiki.openstreetmap.org/wiki/RU:Tag:amenity%3Danimal_shelter) shows full data from [Item:Q6399](https://wiki.openstreetmap.org/wiki/Item:Q6399) (and a bit of wikidata I guess)

It would be cool if Taginfo could show in the same way. If there are parameters in the Wiki then display this data, otherwise display data from osmwikidata/Wikidata. This way we won't have different descriptions in different places.

**Comment by matkoniecz** [comment] 2022-10-03 19:17
See #248

**Comment by drmx** [comment] 2022-10-04 12:01
> So right now https://taginfo.openstreetmap.org/tags/amenity=animal_shelter#wiki is affected, right?
exactly

> This can be also achieved by keeping description at OSM Wiki without using Data Items/Wikidata/Wikibase.
yes, that should work.
I like the idea with data items. this helps to see and process all entries for a tag in one place, but not across multiple pages. The description of the tag is detailed in the article and Infoboxes are needed for unambiguously accurate data for people and programs. There are some other benefits, right?

**Comment by matkoniecz** [comment] 2022-10-04 12:23
> But the wiki page has data

No, this data was removed from Wiki page in [this edit](https://wiki.openstreetmap.org/w/index.php?title=RU:Tag:amenity%3Danimal_shelter&diff=2403706&oldid=2397122) - and infobox is now fetching it from data item

**Comment by drmx** [comment] 2022-10-04 12:48
you're right, I didn't express myself clearly. on the visible page of the browser. not in the wikipage code.

and not so hard to edit.

Do I understand correctly that Taginfo is not flexible and advanced for the same way of working as a wiki page?

**Comment by joto** [comment] 2022-10-04 14:18
Duplicate of #248. Closing.

**Closed by joto** 2022-10-04 14:18 UTC
