### ISSUE TITLE
Description in a chosen language

### ISSUE THREAD

**Issue by maro-21** [taginfo/taginfo#283] opened 2020-07-22 21:38 UTC
https://taginfo.openstreetmap.org/keys/shop#values
Why does Taginfo show Description in my language only when a Wiki page in that language exists?
The Item entry for my language is filled in but it still shows an English description.

**Comment by joto** [comment] 2020-07-23 15:27
Taginfo gets the description from the Wiki page, so naturally it can only show one if there is a wiki page. I am not sure what you mean by "Item entry".

**Comment by maro-21** [comment] 2020-07-24 16:35
"Item entry" - Wikidata item https://wiki.openstreetmap.org/wiki/Data_items

I've recently added descriptions and wiki page for `shop=mobile_phone` in Polish:
https://wiki.openstreetmap.org/wiki/Pl:Tag:shop%3Dmobile_phone
https://wiki.openstreetmap.org/wiki/Item:Q6565
On both pages the description is "Sklep sprzedający telefony komórkowe i akcesoria."
But on Taginfo it's still in English:
https://taginfo.openstreetmap.org/tags/?key=shop&value=mobile_phone

How long should we wait for Taginfo to update?

![Taginfo](https://user-images.githubusercontent.com/57260466/88413610-bebfe380-cddb-11ea-96b5-ac5fa7b91c8a.png)

**Comment by joto** [comment] 2020-07-24 20:23
Ah, this has something to do with the wikidata stuff. Taginfo doesn't support that. See #248.

**Comment by maro-21** [comment] 2020-08-16 12:55
So what are data items for?
I thought they were created to make parsing easier for external tools.

https://wiki.openstreetmap.org/wiki/Data_items :
_"Tools, such as iD editor and **Taginfo** are now able to get tag information without complex and error-prone parsing of the wiki markup."_

So why is Taginfo taking information from wiki tables instead of data items?

I went to taginfo/shops and was starting to add missing translations for shops. It's fast and easy to add a translation to a Wiki Data Item. And after it it's immediately visible in iD editor.
![iD-information](https://user-images.githubusercontent.com/57260466/88234504-4fca7980-cc79-11ea-9cb8-7489ac560a47.png)

I would like to fully translate descriptions into my language.
But I'm not going to create a Wiki entry for every missing tag because it will take ages. Adding a description to data items takes 20 seconds. And creating a Wiki page takes a lot of time.

I wanted to add descriptions for all traffic signs, but I'm not going to create Wiki pages for them...
https://taginfo.openstreetmap.org/keys/traffic_sign#values + "PL" prefix

Are you planning to fix this?

**Comment by joto** [comment] 2020-08-16 18:40
I believe this is a duplicate of #248.

**Closed by joto** 2020-08-16 18:40 UTC

**Comment by susosl** [comment] 2021-10-09 16:05
#248 talks about using data items _instead_ of the wiki text, but at this time maybe it would be better to use data items _along with_ wiki text (i.e., maintain the wiki parsing and use the data item only when there is no wiki page for that tag and language). This would solve this issue without forcing the wiki community to choose between one system or the other.
