### ISSUE TITLE
Make value column smaller on mobile

### ISSUE THREAD

**Issue by matkoniecz** [taginfo/taginfo#307] opened 2020-12-22 11:53 UTC
I am aware of #144 - also, please let me know if making such reports is not useful. Or maybe it is useful iff pull request is also planned?

But I think that there are some seemingly easy to implement changes that can make mobile much more usable.

For example, is it feasible to default to much smaller column size of value on small screens?

![screen02](https://user-images.githubusercontent.com/899988/102885974-87ba3080-4454-11eb-9a25-c4ba11f839fb.jpg)

**Comment by matkoniecz** [comment] 2020-12-22 11:55
In general it seems that the first column is oversized on mobile.

![screen03](https://user-images.githubusercontent.com/899988/102886166-ea133100-4454-11eb-95a6-73ee80860762.jpg)

**Comment by joto** [comment] 2020-12-22 13:19
This just shows two specific cases where a smaller column width would be better. But what about longer values or higher counts which need more space? This doesn't help with the underlying problem. Fiddling with this might look like an easy change, but it is not. It will just lead to more fiddling down the line when we find other cases that are slightly different. 

Closing as duplicate of #144.

**Closed by joto** 2020-12-22 13:19 UTC
